name: Build/Release
on:
  push:
    branches:
      - main
    tags:
      - 'v*' # 当你推送以 v 开头的标签时触发，例如 v1.0.0
  workflow_dispatch: # 允许手动触发

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build Frontend/Backend
        run: npm run build

      - name: Package Application
        run: npm run make
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: hc-ssh-${{ matrix.os }}
          path: out/make/**/*
